# Generated by Django 3.2.8 on 2023-02-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('repository_url', models.URLField()),
                ('users', models.ManyToManyField(to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_do', models.TextField(null=True)),
                ('create_or_update_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.users')),
            ],
        ),
    ]
