# Generated by Django 3.2.8 on 2023-02-14 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='create_or_update_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='create_or_update',
            field=models.DateField(default=datetime.date(2023, 2, 14)),
        ),
    ]
