# Generated by Django 3.2.8 on 2023-03-14 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20230214_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_or_update',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
