# Generated by Django 3.2.8 on 2023-03-16 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20230314_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_or_update',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
